#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab012_1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Loads led driver
# Description:       Loads led driver
### END INIT INFO

case "$1" in
    start)
    	modprobe led
    	;;
    restart|force-reload)
    	rmmod led
	modprobe led
	;;
    stop)
    	rmmod led
	;;
    status)
    	lsmod | grep led
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
